---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
    tier: backend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
      tier: backend
  template:
    metadata:
      labels:
        app: db
        tier: backend
        version: v1
    spec:
      initContainers:
      - name: init-metadata
        image: harbor.kolon.local/library/busybox:1.36
        command: ["/bin/sh", "-c", "echo -n $POD_NAME > /pod-info/index.html"]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: pod-info
          mountPath: /pod-info
      containers:
      - name: mysql
        image: harbor.kolon.local/library/mysql:8.0
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-password
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/mysql
        - name: db-config
          mountPath: /etc/mysql/conf.d
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "localhost"]
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["mysqladmin", "ping", "-h", "localhost"]
          initialDelaySeconds: 10
          periodSeconds: 5
      - name: metadata-sidecar
        image: harbor.kolon.local/library/busybox:1.36
        command: ["httpd", "-f", "-p", "8081", "-h", "/pod-info"]
        ports:
        - containerPort: 8081
          name: metadata
        volumeMounts:
        - name: pod-info
          mountPath: /pod-info
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: db-pvc
      - name: db-config
        configMap:
          name: db-config
      - name: pod-info
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
    tier: backend
spec:
  selector:
    app: db
    tier: backend
  clusterIP: None
  ports:
  - port: 3306
    targetPort: 3306
    name: tcp-mysql
  - port: 8081
    targetPort: 8081
    name: http-metadata
