---
# ?¤ì„?¤í˜?´ìŠ¤ ê¸°ë³¸ mTLS ?¤ì • (STRICT)
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default

spec:
  mtls:
    mode: STRICT
---
# Web ?°ì–´???¸ë? ?¸ë˜???¼ë°˜ HTTP)???˜ì‹ ?´ì•¼ ?˜ë?ë¡?PERMISSIVE
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: web-peerauthentication

spec:
  selector:
    matchLabels:
      app: web
  mtls:
    mode: PERMISSIVE
---
# Web ?°ì–´ ?‘ê·¼ ?ˆìš© (Ingress Gateway ??Web)
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: web-access-policy

spec:
  selector:
    matchLabels:
      app: web
  action: ALLOW
  rules:
  - from:
    - source:
        # ?¸ê·¸?ˆìŠ¤ ê²Œì´?¸ì›¨?´ì˜ IDë¥??ˆìš© (?¼ë°˜?ìœ¼ë¡?istio-ingressgateway)
        namespaces: ["istio-system"]
---
# WAS ?°ì–´ ?‘ê·¼ ?ˆìš© (Web ??WAS)
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: was-access-policy

spec:
  selector:
    matchLabels:
      app: was
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/3tier-app-32/sa/default"]
    to:
    - operation:
        ports: ["8080"]
---
# WAS ??DB ?‘ê·¼ë§??ˆìš©?˜ëŠ” AuthorizationPolicy
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: db-access-policy

spec:
  selector:
    matchLabels:
      app: db
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/3tier-app-32/sa/default"]
    to:
    - operation:
        ports: ["3306"]
