# 네임스페이스 기본 mTLS 설정 (STRICT)
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: STRICT
---
# Web 티어에는 외부 접속을 위해 PERMISSIVE 허용 (Gateway 통신용)
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: web-peerauthentication
spec:
  selector:
    matchLabels:
      app: web
  mtls:
    mode: PERMISSIVE
