---
# 1. 보안 설정: 우선 접속 허용을 위해 PERMISSIVE로 설정
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: ${NAMESPACE}
spec:
  mtls:
    mode: PERMISSIVE
---
# 2. 인가 정책: 게이트웨이의 웹 접속 허용
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: web-access-policy
  namespace: ${NAMESPACE}
spec:
  selector:
    matchLabels:
      app: web
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["istio-system"]
---
# 3. 게이트웨이 설정 (포트 80 오픈)
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: 3tier-gateway
  namespace: ${NAMESPACE}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
# 4. 대상 규칙(DestinationRule): 모든 티어 통합
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: all-destinationrules
  namespace: ${NAMESPACE}
spec:
  host: web
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v1
    labels: { version: v1 }
  - name: v2
    labels: { version: v2 }
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: was-destination
  namespace: ${NAMESPACE}
spec:
  host: was
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v1
    labels: { version: v1 }
  - name: v2
    labels: { version: v2 }
  - name: v3
    labels: { version: v3 }
  - name: v4
    labels: { version: v4 }
---
# 5. 가상 서비스(VirtualService): 외부 및 내부 라우팅 통합
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: 3tier-routing
  namespace: ${NAMESPACE}
spec:
  hosts:
  - "*"
  gateways:
  - 3tier-gateway
  http:
  - route:
    - destination:
        host: web
        subset: v1
      weight: 50
    - destination:
        host: web
        subset: v2
      weight: 50
    headers:
      response:
        set:
          Cache-Control: "no-store, no-cache, must-revalidate"
