---
# 1. 보안 설정: 접속 허용을 위해 PERMISSIVE로 원복
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
  namespace: 3tier-app-23
spec:
  mtls:
    mode: PERMISSIVE
---
# 2. 인가 정책: 게이트웨이 접속 허용
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: web-access-policy
  namespace: 3tier-app-23
spec:
  selector:
    matchLabels:
      app: web
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["istio-system"]
---
# 3. 게이트웨이 및 라우팅 통합
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: 3tier-gateway
  namespace: 3tier-app-23
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: web-destination
  namespace: 3tier-app-23
spec:
  host: web
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v1
    labels: { version: v1 }
  - name: v2
    labels: { version: v2 }
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: was-destination
  namespace: 3tier-app-23
spec:
  host: was
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
  subsets:
  - name: v1
    labels: { version: v1 }
  - name: v2
    labels: { version: v2 }
  - name: v3
    labels: { version: v3 }
  - name: v4
    labels: { version: v4 }
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: web-external-routing
  namespace: 3tier-app-23
spec:
  hosts:
  - "*"
  gateways:
  - 3tier-gateway
  http:
  - route:
    - destination:
        host: web
        subset: v1
      weight: 50
    - destination:
        host: web
        subset: v2
      weight: 50
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: was-virtualservice
  namespace: 3tier-app-23
spec:
  hosts:
  - was
  http:
  - route:
    - destination:
        host: was
        subset: v1
      weight: 25
    - destination:
        host: was
        subset: v2
      weight: 25
    - destination:
        host: was
        subset: v3
      weight: 25
    - destination:
        host: was
        subset: v4
      weight: 25
