---
# 1. ?∏Ï¶ù Î∞?Î≥¥Ïïà ?§Ï†ï (PeerAuthentication)
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default

spec:
  mtls:
    mode: STRICT
---
# 2. ?∏Í? ?ïÏ±Ö (AuthorizationPolicy)
# Gateway -> Web (?¥Îãπ ?§ÏûÑ?§Ìéò?¥Ïä§ ?¥Ïùò Í≤åÏù¥?∏Ïõ®???åÎìú?êÏÑú ?§Îäî ?∏Îûò???àÏö©)
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: web-access-policy

spec:
  selector:
    matchLabels:
      app: web
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["3tier-app-31", "istio-system"]
---
# Web -> WAS
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: was-access-policy

spec:
  selector:
    matchLabels:
      app: was
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/3tier-app-32/sa/default"]
---
# WAS -> DB
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: db-access-policy

spec:
  selector:
    matchLabels:
      app: db
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/3tier-app-32/sa/default"]
---
# 3. ?Ä??Í∑úÏπô (DestinationRule)
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: web-destination

spec:
  host: web
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels: { version: v1 }
  - name: v2
    labels: { version: v2 }
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: was-destination

spec:
  host: was
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels: { version: v1 }
  - name: v2
    labels: { version: v2 }
  - name: v3
    labels: { version: v3 }
  - name: v4
    labels: { version: v4 }
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: db-destination

spec:
  host: db
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
# 4. ?ºÏö∞???§Ï†ï (VirtualService - ?∏Î? ?∏Îûò?ΩÏö©)
# ?ÑÏö© Istio ?∞Îèô ?ºÏö∞??
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: web-external-route

spec:
  gateways:
  - 3tier-gateway
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: web
        port:
          number: 80
---
# 5. Í∞Ä???úÎπÑ??(VirtualService - ?¥Î? Î©îÏãú ?∏Îûò?ΩÏö©)
# Web ?¥Î???v1/v2 Í∞ÄÏ§ëÏπò Î∂ÑÏÇ∞
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: web-internal

spec:
  hosts:
  - web
  http:
  - route:
    - destination:
        host: web
        subset: v1
      weight: 50
    - destination:
        host: web
        subset: v2
      weight: 50
---
# WAS ?¥Î? v1~v4 Í∞ÄÏ§ëÏπò Î∂ÑÏÇ∞
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: was-internal

spec:
  hosts:
  - was
  http:
  - route:
    - destination:
        host: was
        subset: v1
      weight: 25
    - destination:
        host: was
        subset: v2
      weight: 25
    - destination:
        host: was
        subset: v3
      weight: 25
    - destination:
        host: was
        subset: v4
      weight: 25
---
# DB ?¥Î? TCP ?ºÏö∞??
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: db-internal

spec:
  hosts:
  - db
  tcp:
  - match:
    - port: 3306
    route:
    - destination:
        host: db
        port:
          number: 3306
