---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: was-destination
  namespace: ${NAMESPACE}
spec:
  host: was
  trafficPolicy:
    loadBalancer:
      simple: RANDOM # 세션 고정 방지를 위해 랜덤 로드밸런싱 적용
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3
  - name: v4
    labels:
      version: v4
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: web-destination
  namespace: ${NAMESPACE}
spec:
  host: web
  trafficPolicy:
    loadBalancer:
      simple: RANDOM # 웹 서버도 랜덤하게 선택되도록 설정
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: web-external-routing
  namespace: 3tier-app-13
spec:
  hosts:
  - "*"
  gateways:
  - 3tier-gateway
  http:
  - route:
    - destination:
        host: web
        subset: v1
      weight: 50
    - destination:
        host: web
        subset: v2
      weight: 50
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: was-virtualservice
  namespace: ${NAMESPACE}
spec:
  hosts:
  - was
  http:
  - match:
    - sourceLabels:
        app: web
        version: v1
    route:
    - destination:
        host: was
        subset: v1
      weight: 50
    - destination:
        host: was
        subset: v2
      weight: 50
  - match:
    - sourceLabels:
        app: web
        version: v2
    route:
    - destination:
        host: was
        subset: v3
      weight: 50
    - destination:
        host: was
        subset: v4
      weight: 50
  - route: # Default fallback
    - destination:
        host: was
        subset: v1
      weight: 25
    - destination:
        host: was
        subset: v2
      weight: 25
    - destination:
        host: was
        subset: v3
      weight: 25
    - destination:
        host: was
        subset: v4
      weight: 25
