apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: 3tier-gateway
  namespace: 3tier-app-25
  annotations:
    networking.istio.io/service-type: LoadBalancer
    networking.istio.io/service-external-traffic-policy: Local
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
