---
# 외부 트래픽 → Web 라우팅 (Gateway API HTTPRoute)
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: web-route
  namespace: 3tier-app
spec:
  parentRefs:
  - name: 3tier-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: web
      port: 80
    timeouts:
      request: 30s
      backendRequest: 10s
---
# Web → WAS 내부 라우팅 (서비스 메시 내부 트래픽 제어)
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: was-virtualservice
  namespace: 3tier-app
spec:
  hosts:
  - was
  http:
  - route:
    - destination:
        host: was
        subset: v1
        port:
          number: 8080
      weight: 100
    timeout: 60s
    retries:
      attempts: 3
      perTryTimeout: 15s
      retryOn: 5xx,reset,connect-failure,retriable-4xx
    fault:
      delay:
        percentage:
          value: 0
        fixedDelay: 0s
    headers:
      request:
        add:
          x-forwarded-by: "web-tier"
      response:
        add:
          x-served-by: "was-tier"
---
# WAS → DB 내부 라우팅 (TCP 트래픽 제어)
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: db-virtualservice
  namespace: 3tier-app
spec:
  hosts:
  - db
  tcp:
  - match:
    - port: 3306
    route:
    - destination:
        host: db
        subset: v1
        port:
          number: 3306
      weight: 100
