---
# Istio 네이티브 Gateway (기존 istio-ingressgateway 사용)
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: 3tier-gateway
  namespace: 3tier-app-22
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
