---
# 1. 인증 및 보안 설정 (PeerAuthentication)
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: STRICT
---
# 2. 인가 정책 (AuthorizationPolicy)
# Gateway -> Web (해당 네임스페이스 내의 게이트웨이 파드에서 오는 트래픽 허용)
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: web-access-policy
spec:
  selector:
    matchLabels:
      app: web
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["${NAMESPACE}", "istio-system"]
---
# Web -> WAS
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: was-access-policy
spec:
  selector:
    matchLabels:
      app: was
  action: ALLOW
  rules:
  - from:
    - source:
<<<<<<< HEAD
        principals: ["cluster.local/ns/${NAMESPACE}/sa/default"]
=======
        principals: ["cluster.local/ns/3tier-app-38/sa/default"]
>>>>>>> c54d8acd2a29bfe64fa57e6fd6bf9b9c730ae459
---
# WAS -> DB
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: db-access-policy
spec:
  selector:
    matchLabels:
      app: db
  action: ALLOW
  rules:
  - from:
    - source:
<<<<<<< HEAD
        principals: ["cluster.local/ns/${NAMESPACE}/sa/default"]
=======
        principals: ["cluster.local/ns/3tier-app-38/sa/default"]
>>>>>>> c54d8acd2a29bfe64fa57e6fd6bf9b9c730ae459
---
# 3. 대상 규칙 (DestinationRule)
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: web-destination
spec:
  host: web
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels: { version: v1 }
  - name: v2
    labels: { version: v2 }
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: was-destination
spec:
  host: was
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels: { version: v1 }
  - name: v2
    labels: { version: v2 }
  - name: v3
    labels: { version: v3 }
  - name: v4
    labels: { version: v4 }
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: db-destination
spec:
  host: db
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
# 4. 라우팅 설정 (VirtualService - 외부 트래픽용)
# 전용 Istio 연동 라우팅 
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: web-external-route
spec:
  gateways:
  - 3tier-gateway
  hosts:
  - "*"
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: web
        port:
          number: 80
---
# 5. 가상 서비스 (VirtualService - 내부 메시 트래픽용)
# Web 내부의 v1/v2 가중치 분산
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: web-internal
spec:
  hosts:
  - web
  http:
  - route:
    - destination:
        host: web
        subset: v1
      weight: 50
    - destination:
        host: web
        subset: v2
      weight: 50
---
# WAS 내부 v1~v4 가중치 분산
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: was-internal
spec:
  hosts:
  - was
  http:
  - route:
    - destination:
        host: was
        subset: v1
      weight: 25
    - destination:
        host: was
        subset: v2
      weight: 25
    - destination:
        host: was
        subset: v3
      weight: 25
    - destination:
        host: was
        subset: v4
      weight: 25
---
# DB 내부 TCP 라우팅
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: db-internal
spec:
  hosts:
  - db
  tcp:
  - match:
    - port: 3306
    route:
    - destination:
        host: db
        port:
          number: 3306
