---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: was-destination
  namespace: ${NAMESPACE}
spec:
  host: was
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
  - name: v3
    labels:
      version: v3
  - name: v4
    labels:
      version: v4
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: web-destination
  namespace: ${NAMESPACE}
spec:
  host: web
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: db-destination
  namespace: ${NAMESPACE}
spec:
  host: db
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: web-external-routing
  namespace: ${NAMESPACE}
spec:
  hosts:
  - "*"
  gateways:
  - 3tier-gateway
  http:
  - route:
    - destination:
        host: web
        subset: v1
      weight: 50
    - destination:
        host: web
        subset: v2
      weight: 50
    headers:
      response:
        set:
          Cache-Control: "no-store, no-cache, must-revalidate"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: was-virtualservice
  namespace: ${NAMESPACE}
spec:
  hosts:
  - was
  http:
  - match:
    - sourceLabels:
        app: web
        version: v1
    route:
    - destination:
        host: was
        subset: v1
      weight: 50
    - destination:
        host: was
        subset: v2
      weight: 50
  - match:
    - sourceLabels:
        app: web
        version: v2
    route:
    - destination:
        host: was
        subset: v3
      weight: 50
    - destination:
        host: was
        subset: v4
      weight: 50
  - route: # Default fallback
    - destination:
        host: was
        subset: v1
      weight: 25
    - destination:
        host: was
        subset: v2
      weight: 25
    - destination:
        host: was
        subset: v3
      weight: 25
    - destination:
        host: was
        subset: v4
      weight: 25
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: db-virtualservice
  namespace: ${NAMESPACE}
spec:
  hosts:
  - db
  tcp:
  - match:
    - port: 3306
    route:
    - destination:
        host: db
        subset: v1
        port:
          number: 3306
