---
# 네임스페이스 기본 mTLS 설정 (STRICT)
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default
spec:
  mtls:
    mode: STRICT
---
# Web 티어만 외부 대응을 위해 PERMISSIVE 허용 (Gateway 통신용)
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: web-peerauthentication
spec:
  selector:
    matchLabels:
      app: web
  mtls:
    mode: PERMISSIVE
---
# Web 인가 정책 (Gateway -> Web)
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: web-access-policy
spec:
  selector:
    matchLabels:
      app: web
  action: ALLOW
  rules:
  - from:
    - source:
        namespaces: ["${NAMESPACE}", "istio-system"]
---
# WAS 인가 정책 (Web -> WAS)
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: was-access-policy
spec:
  selector:
    matchLabels:
      app: was
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/${NAMESPACE}/sa/default"]
---
# DB 인가 정책 (WAS -> DB)
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: db-access-policy
spec:
  selector:
    matchLabels:
      app: db
  action: ALLOW
  rules:
  - from:
    - source:
        principals: ["cluster.local/ns/${NAMESPACE}/sa/default"]