# ?몃? ?몃옒?쎌쓣 ?꾪븳 Web ?쇱슦??(Istio VirtualService + Gateway)
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: web-virtualservice

spec:
  hosts:
  - "*"
  gateways:
  - 3tier-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: web
        subset: v1
        port:
          number: 80
      weight: 100
    timeout: 30s
    retries:
      attempts: 3
      perTryTimeout: 10s
      retryOn: 5xx,reset,connect-failure
---
# Web?먯꽌 WAS ?대? ?쇱슦??(?쒕퉬??硫붿떆 ?대? ?몃옒???쒖뼱)
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: was-virtualservice

spec:
  hosts:
  - was
  http:
  - route:
    - destination:
        host: was
        subset: v1
        port:
          number: 8080
      weight: 100
    timeout: 60s
    retries:
      attempts: 3
      perTryTimeout: 15s
      retryOn: 5xx,reset,connect-failure,retriable-4xx
    headers:
      request:
        add:
          x-forwarded-by: "web-tier"
      response:
        add:
          x-served-by: "was-tier"
---
# WAS?먯꽌 DB ?대? ?쇱슦??(TCP ?몃옒???쒖뼱)
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: db-virtualservice

spec:
  hosts:
  - db
  tcp:
  - match:
    - port: 3306
    route:
    - destination:
        host: db
        subset: v1
        port:
          number: 3306
      weight: 100
