apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: 3tier-gateway
  namespace: 3tier-app-30
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
