---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: was
  namespace: 3tier-app
  labels:
    app: was
    tier: middleware
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: was
      tier: middleware
  template:
    metadata:
      labels:
        app: was
        tier: middleware
        version: v1
    spec:
      containers:
      - name: tomcat
        image: tomcat:10.1-jdk17
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: was-config
              key: JAVA_OPTS
        - name: CATALINA_OPTS
          valueFrom:
            configMapKeyRef:
              name: was-config
              key: CATALINA_OPTS
        - name: DB_HOST
          value: "db"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-database
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: mysql-password
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        volumeMounts:
        - name: was-config-volume
          mountPath: /opt/app/config
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: was-config-volume
        configMap:
          name: was-config
          items:
          - key: application.properties
            path: application.properties
---
apiVersion: v1
kind: Service
metadata:
  name: was
  namespace: 3tier-app
  labels:
    app: was
    tier: middleware
spec:
  selector:
    app: was
    tier: middleware
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: was-hpa
  namespace: 3tier-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: was
  minReplicas: 2
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
