---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-v1
  namespace: 3tier-app-26
  labels:
    app: web
    tier: frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      tier: frontend
      version: v1
  template:
    metadata:
      labels:
        app: web
        tier: frontend
        version: v1
    spec:
      containers:
      - name: nginx
        image: harbor.kolon.local/library/nginx:1.25
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: web-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: web-config
        configMap:
          name: web-config
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-v2
  namespace: 3tier-app-26
  labels:
    app: web
    tier: frontend
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
      tier: frontend
      version: v2
  template:
    metadata:
      labels:
        app: web
        tier: frontend
        version: v2
    spec:
      containers:
      - name: nginx
        image: harbor.kolon.local/library/nginx:1.25
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: web-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: web-config
        configMap:
          name: web-config
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: 3tier-app-26
  labels:
    app: web
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: web
    tier: frontend
  ports:
  - port: 80
    targetPort: 80
    name: http
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-v1-hpa
  namespace: 3tier-app-26
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-v2-hpa
  namespace: 3tier-app-26
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-v2
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
